export const BADGE_IDS = {
  SIGIL_FIRST_INFUSION: 'SIGIL_FIRST_INFUSION',
  SIGIL_FIRST_RELEASE: 'SIGIL_FIRST_RELEASE',
  SIGIL_FIRST_VOTE: 'SIGIL_FIRST_VOTE',
  STAMP_TREND_SPARK: 'STAMP_TREND_SPARK',
  STAMP_FEED_DOMINATOR: 'STAMP_FEED_DOMINATOR',
  FRAGMENT_RETURN_2D: 'FRAGMENT_RETURN_2D',
  FRAGMENT_RETURN_7D: 'FRAGMENT_RETURN_7D',
  OBJECT_CROISHORNEY: 'OBJECT_CROISHORNEY',
  OBJECT_EICHHORNEY: 'OBJECT_EICHHORNEY',
  OBJECT_BRAINHORNEY: 'OBJECT_BRAINHORNEY',
} as const;
